name: Build Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        name: build_binary
        path: ./target/debug/hyper-rust-github-actions

  deploy:
    name: Deploy to Remote
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binary file
        uses: actions/download-artifact@v1
        with:
          name: build_binary
      - shell: bash
        run: |
          ls -a
      - name: action-slack
        uses: 8398a7/action-slack@v2.4.2
        with:
          author_name: Zachs Test Action Author
          status: ${{ job.status }}
          icon_emoji: confetti_ball
          text: A deployment has been made!
          mention: channel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required

