name: Build Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        name: build_binary
        path: ./target/hyper-rust-github-actions

  deploy:
    name: Deploy to Remote
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binary file
        uses: actions/download-artifact@v1
        with:
          name: build_binary
      - shell: bash
        run: |
          ls -a